DEFRA/marine-licensing-journey-tests

wdio.browserstack.conf.js
wdio.conf.js

Updating the url for target environment

Fix url for cdp pipeline run

---

test/features/create.notification.feature
test/screenplay/abilities/browse.the.web.js
test/screenplay/actor.js
test/screenplay/interactions/ensure.heading.is.js
test/screenplay/tasks/apply.for.exemption.js
test/steps/stepdefs.js

Converted the sample test to the screenplay pattern.
**Explanation**
Actor: Represents the user performing actions.
Ability: Represents the capability to interact with the browser.
Task: Represents a high-level action, like opening a web page.
Interaction: Represents a low-level action, like ensuring a condition is met.
Test Scenario: Combines the actor, ability, and task to perform a test.

Screenplay implementation

---

wdio.conf.js
wdio.local.conf.js

Change to use CucumberStepReporter

---

wdio.conf.js
wdio.local.conf.js

Enable WDIO steps reporting so there's more information provided on the allure reports:

Wnable wdio steps reporting

---

test-infrastructure/pages/project.name.page.js
test/steps/create.exemption.steps.js

Move page heading to page object

Move page heading to page object

---

PULL_REQUEST_TEMPLATE.md

Introduced a PR template to prompt for the right information when raising a PR.
n/a
n/a

Introduced a PR template

---

test-infrastructure/pages/task.list.page.js
test-infrastructure/screenplay/interactions/ensure.task.is.js
test-infrastructure/screenplay/interactions/select.task.js
test/features/public.register.consent.feature
test/features/view.task.list.feature
test/steps/task.list.steps.js

This PR is only intended to fix existing tests to work with the latest merge.  A further branch and PR will be created for the new tests related to ML-16
- Changed `TastListPage` to return locators based on the `taskName` whilst maintaining this abstraction
- Made the SelectTask task more generic and altered the feature files accordingly 
https://eaflood.atlassian.net/browse/ML-16
- The xpath locators work but I might seek to improve them later - at least they are held in a single place if further changes are needed later - all other code needs no knowledge of the DOM

Updating locators for the task list as the order has changed (making this less brittle)

---

.cursor/rules/README.md
.cursor/rules/bdd.rules.mdc
.cursor/rules/code.generation.mdc
.cursor/rules/htsm.mdc
.cursor/rules/project-structure.mdc
.cursor/rules/screenplay-pattern.mdc

- Created a readme for the cursor rules to help orient new engineers to the project
- A new ruleset for writing good gherkin
- A new ruleset for cursor to follow when generating code
- Some minor changes to existing rulesets

Additional cursor rules added

---

.cursor/rules/code.generation.mdc

Improving code generation rules

Improving code generation rules

---

.cursor/rules/README.md
.cursor/rules/htsm.mdc
.cursor/rules/playbook.general.rules.mdc
.cursor/rules/playbook.refactoring.mdc
.cursor/rules/playbook.styleguide.mdc
README.md
test-infrastructure/screenplay/interactions/ensure.task.list.contains.js

Fix standards violations, spelling errors, introduce some new playbooks and update readme

Fix standards violations, spelling errors, introduce some new playbooks and update readme

---

.cursor/rules/README.md
.cursor/rules/playbook.clean.code.mdc
.cursor/rules/playbook.refactoring.mdc
README.md

Introducing stronger guidelines on code quality and smells
- Link to relevant Jira tickets or GitHub issues, if applicable.

Introducing stronger guidelines on code quality and smells

---

.cursor/rules/README.md
.cursor/rules/application.under.test.mdc
.cursor/rules/personas.mdc
.gitignore
README.md

Introduce rules for cursor that explain the system under test

Introduce rules for cursor that explain the system under test

---

.cursor/rules/README.md
.cursor/rules/playbook.refactoring.mdc
.cursor/rules/responsible.ai.use.mdc

Creating guidance for responsible AI usage and refactoring guidelines based on research papers

Creating guidance for responsible AI usage and refactoring guidelines based on research papers

---

test-infrastructure/screenplay/tasks/fill.form.js

- Refactored the `FillForm` task class to reduce code duplication by extracting common patterns.
- Implemented helper methods to create consistent handling for page imports and element interactions.
- Related to code duplication issue flagged in static analysis.
- This change follows the DRY principle by extracting repetitive code into reusable helper methods.
- The functionality remains unchanged but the code is now more maintainable.
- Added proper async/await handling for promises in additional actions.

Remove duplicated code blocks to adhere to DRY principle

---

.cursor/README.md
.cursor/RULES-OPTIMISATION.md
.cursor/cursor.rules.json
.cursor/rules/README.md
.cursor/rules/application.under.test.mdc
.cursor/rules/avoid.over.engineering.mdc
.cursor/rules/documentation.coherence.mdc
.cursor/rules/examples.md
.cursor/rules/personas.mdc
.cursor/rules/scenario-testing.mdc
.cursor/rules/stop.overengineering.and.making.stuff.up.mdc
.cursor/rules/summaries/personas.summary.md
.cursor/rules/test-charters.mdc
.cursor/rules/test-strategy.integration.mdc
.cursor/rules/user.stories.and.test.coverage.mdc

This PR updates the Cursor rules system to improve consistency, follow British English standards, and reduce duplication by referencing existing resources.
1. **Standardized British English spelling** across all rule documentation
- Updated American spellings (optimize → optimise, organize → organise)
- Renamed `RULES-OPTIMIZATION.md` to `RULES-OPTIMISATION.md`
- Fixed all references to maintain link integrity
2. **Replaced duplicated personas with references to established ones**
- Updated `personas.mdc` to point to existing personas in `documentation/personas/`
- Modified persona summary to reflect this referencing approach
- Ensured all rules correctly reference the official personas
3. **Enhanced rules for better coherence**
- Added "Documentation Resource Reuse" section to …

Updates the Cursor rules system to improve consistency, follow British English standards, and reduce duplication by referencing existing resources.

---

test/features/site.details.manual.circle.feature
test/steps/site.details.steps.js

- This change changes existing tests to anticipate the changes in the flow delivered by ML-35
- New tests for this feature are currently in development
- ML-35

Update existing tests based on change to flow implemented by ML-35

---

wdio.conf.js

Remove multithreading from test environment

Remove multithreading from test environment

---

wdio.conf.js
wdio.local.conf.js

Increase timeout as some steps do a lot of processing now

Increase timeout as some steps do a lot of processing now

---

wdio.conf.js

Feat/implement change chromedriver proxy config to fix Defra ID issues

Feat/implement change chromedriver proxy config to fix Defra ID issues

---

Dockerfile
wdio.conf.js
wdio.local.conf.js

Install playwright dependencies and fix new tagging issue

Install playwright dependencies and fix new tagging issue

---

Dockerfile
test-infrastructure/screenplay/abilities/browse.d365.js

Use installed chromium binary on Alpine

Use installed chromium binary on Alpine

---

Dockerfile

set HEADLESS=true for playwright

set HEADLESS=true for playwright

---

test-infrastructure/screenplay/tasks/login.to.d365.js

- **Purpose**: Enable D365 authentication to work correctly when deployed on the DEFRA Core Delivery Platform (CDP) by implementing HTTP proxy support.
- **Motivation**: CDP automatically injects an `HTTP_PROXY` environment variable for outbound network requests. The existing D365 login task used direct `fetch()` calls which would fail in the CDP environment.
- **Changes**: Updated `login.to.d365.js` to use a proxy-aware fetch implementation that automatically detects and uses the CDP proxy when available, whilst maintaining backwards compatibility for local development.
- Related to CDP deployment requirements for marine licensing test automation
- Addresses network connectivity issues when running D365 integration tests in CDP environment …

Add CDP Proxy Support for D365 Authentication

---

test-infrastructure/screenplay/abilities/browse.d365.js
test-infrastructure/screenplay/interactions/ensure.that.the.exemption.details.are.correct.js
test-infrastructure/screenplay/interactions/launch.d365.js
test-infrastructure/screenplay/tasks/view.submitted.exemption.notification.js

Add additional debugging information and attach to the allure report

Add additional debugging information and attach to the allure report

---

Dockerfile
test-infrastructure/screenplay/abilities/browse.d365.js

Install playwright dependencies and remove config to use alpine chrome

Install playwright dependencies and remove config to use alpine chrome

---

Dockerfile
test-infrastructure/screenplay/abilities/browse.d365.js

Reverts DEFRA/marine-licensing-journey-tests#90

Revert "Install playwright dependencies and remove config to use alpine chrome"

---

test-infrastructure/screenplay/interactions/ensure.site.details.js

- Addressed code health issues related to high cyclomatic complexity in `ensure.site.details.js`
- Applied "Extract Complex Conditionals" refactoring pattern to improve maintainability
- Reduced the number of conditional statements across the implementation
- `determineExpectedMethod()` - Handles method determination logic
- `verifyCoordinateDisplayBySiteType()` - Coordinates site type verification
- `verifyCircleSiteDisplay()` & `verifyBoundarySiteDisplay()` - Specific display verifications
- `validateFileType()` & `validateExpectedCoordinates()` - Validation helpers
- `verifyUploadedFileName()` & `getActualCoordinatesText()` - Focused utility methods
- **Reduced complexity**: Each method has single, clear responsibility
- **Improved readability**: Method names express intent without …

Refactoring: Reduce Complexity in EnsureSiteDetails

---

documentation/README.md
documentation/test-strategy/README.md
documentation/test-strategy/accessibility.md
documentation/test-strategy/bdd-rules.md
documentation/test-strategy/domain-context.md
documentation/test-strategy/heuristics.md
documentation/test-strategy/investigative-testing-advanced.md
documentation/test-strategy/investigative-testing-examples.md

Minor updates to documentation to fix broken links

Minor updates to documentation to fix broken links

---

documentation/user-stories/ML-140.file.upload.check.your.answers.md
documentation/user-stories/README.md
test-infrastructure/pages/check.your.answers.page.js
test-infrastructure/screenplay/factories/builder-extensions.js
test-infrastructure/screenplay/factories/exemption.factory.js
test-infrastructure/screenplay/factories/site-details.factory.js
test-infrastructure/screenplay/interactions/ensure.check.your.answers.page.js
test-infrastructure/screenplay/tasks/complete.site.details.js
test/features/check.your.answers.feature
test/steps/check.your.answers.steps.js

This PR implements comprehensive journey test coverage for **ML-140: File upload check your answers**, establishing a new complementary test architecture that combines high-level Gherkin scenarios with detailed frontend integration tests.
**Purpose:** Validate that the "Check your answers" page correctly displays uploaded file details (KML/Shapefile) while demonstrating an optimised test strategy that balances comprehensive coverage with maintainable, efficient test execution.
**Key Changes:**
- Added concise Gherkin scenarios for KML and Shapefile upload validation
- Extended step definitions to handle file upload check your answers scenarios
- Enhanced screenplay interactions and page objects for file upload support
- Fixed [critical backend validation …

ML-140: File Upload Check Your Answers - Journey Tests Implementation

---

test-infrastructure/screenplay/interactions/ensure.dashboard.displays.notification.js

- 'Exempt activity' label has changed to 'Exempt activity notification' so update an assertion for the dashboard to look for this
[- Link to relevant Jira tickets or GitHub issues, if applicable.](https://eaflood.atlassian.net/browse/ML-488)

ML-488 - Look for updated exempt activity label on dashboard

---

documentation/user-stories/ML-543.service.name.md

Add a minor change to force a new docker image to be built

Add a minor change to force a new docker image to be built

---

test-infrastructure/pages/dashboard.page.js
test-infrastructure/pages/header.page.js

- Change nav link text from "Projects home" to "Projects"
- Link to relevant Jira tickets or GitHub issues, if applicable.

ML-20 - Update nav link to 'Projects'

---

test-infrastructure/screenplay/tasks/navigate.to.dashboard.js

- The Projects nav link has been removed from project name page, so if the tests need to navigate from there to the dashboard, do it by changing URL
- Link to relevant Jira tickets or GitHub issues, if applicable.

ML-20 - Navigate to dashboard from project name page using URL not Projects nav link

---

test-infrastructure/screenplay/interactions/ensure.dashboard.sort.order.js

- Clearly explain the purpose and motivation behind this pull request.
- Detail the changes introduced.
Depends-On: https://github.com/DEFRA/marine-licensing-frontend/pull/175
Depends-On: https://github.com/DEFRA/marine-licensing-backend/pull/65
- https://eaflood.atlassian.net/browse/ML-591

ML-591 - Update dashboard test to use Active status not Closed

---

.github/workflows/run-tests-and-publish.yml

Allow manual dispatch of github action

Allow manual dispatch of github action

---

test-infrastructure/screenplay/factories/site-details.factory.js

Refactor to remove code duplication

Refactor to remove code duplication

---

.github/workflows/check-pull-request.yml
run-journey-tests/action.yml

Journey tests now add a PR comment with summary results

Add a pr comment for the journey tests showing the results

---

test-infrastructure/screenplay/tasks/complete.activity.dates.js

Minor refactor to improve code health

Minor refactor to improve code health

---

run-journey-tests/action.yml

- changes required for the logic to fetch branch from the pr description of frontend or backend if there are any journey tests depends on set

ML-648 further changes on depends on logic
